version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/live-chat

hooks:
  BeforeInstall:
    - runas: ec2-user
      timeout: 300
      # 必要な依存関係のインストール
      script: |
        cd /home/ec2-user/live-chat
        yarn install
  ApplicationStop:
    - runas: ec2-user
      timeout: 300
      # 既存のアプリケーションを停止
      script: |
        pm2 stop next-app || true
        pm2 delete next-app || true
  ApplicationStart:
    - runas: ec2-user
      timeout: 300
      # アプリを起動
      script: |
        cd /home/ec2-user/live-chat
        yarn build
        pm2 start yarn --name "next-app" -- start
        pm2 save
