version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/live-chat
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ec2-user
