version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/live-chat
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
      timeout: 300
      commands:
        - bash scripts/application_stop.sh
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
      timeout: 300
      commands:
        - bash scripts/application_start.sh
