version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/live-chat
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - runas: root
      timeout: 300
      location: scripts/application_stop.sh
  AfterInstall:
    - runas: root
      timeout: 300
      location: scripts/before_install.sh
  ApplicationStart:
    - runas: root
      timeout: 300
      location: scripts/application_start.sh
