version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/live-chat
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/live-chat/scripts
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/application_stop.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/application_start.sh
      runas: ec2-user
