version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.17.0
  pre_build:
    commands:
      - npm i -g pnpm@9.15.0
      - pnpm i --frozen-lockfile
  build:
    commands:
      - pnpm build
      - zip -ry build.zip node_modules .next public package.json
artifacts:
  files:
    - 'build.zip'
    - 'appspec.yml'
    - 'scripts/**'
